### ISSUE TITLE
Hi OLUG!!

### ISSUE THREAD

**Issue by jhannah** [jhannah/olug-git-101#1]
Comment on this issue so I can add your github.com account as a github Collaborator. :)

**Comment by choman** [comment]
Chad here. and first one.  BAMM!

**Comment by vonahsen** [comment]
comment

**Comment by rjt** [comment]
Add me to the group.  Reminds me of a cleanup job that never got quite done

**Comment by hwolfe71** [comment]
Here

**Comment by piperfect** [comment]
beep beep

**Comment by piperfect** [comment]
beep beep

**Comment by dakoris73** [comment]
I will be there and looking forward to learning this......

**Comment by dthacker9** [comment]
Comment!

**Comment by jhannah** [comment]
As @rjt pointed out, if you haven't done so already, you may want to add SSH keys, clone this repository, and do a couple test pushes. Or just the SSH key bit. Or just wait for the meeting, and I'll explain the SSH keys. :)

**Comment by sharpestmarble** [comment]
Need to figure out git. I've seen it used lots, never had a chance to use it.

**Comment by sandikbarr** [comment]
Thanks for doing this, Jay! I'll be there and happy to assist with workshop stuff if needed.

**Comment by sandikbarr** [comment]
Gah, I'm not gonna make it. Sorry, Jay! I think it's awesome that you're doing this. You're an excellent mentor and teacher.

**Comment by jhannah** [comment]
@sandikbarr I will once again disprove your assertion this evening. ;)

**Comment by djrushon** [comment]
I'm excited and ready for a great session!

**Comment by relayer370** [comment]
whut?

**Comment by jhannah** [comment]
FYI all -- I renamed this repo to re-use it for another lab. Not sure why you'd care, but it you do this is your heads-up. :)
